name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  docker-push:
    env:
      IMAGE_NAME: "harbor.carrier-mu.src.surf-hosted.nl/carrier/n2n-diagnostics"
      HARBOR_SERVER: "harbor.carrier-mu.src.surf-hosted.nl"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: | 
        pip install poetry
        poetry install --no-root

    - name: Get vantage6-client version
      run: |
        V6_VERSION=poetry run pip list --format=freeze|grep vantage6-client|sed -e 's/[^=]*==\(.*\)/\1/'
        echo V6_TAG=v6-v$V6_VERSION >> $GITHUB_ENV
    
    - name: Docker Login
      #run: echo '${{ secrets.HARBOR_PASSWORD }}' | docker login ${{env.HARBOR_SERVER}} --username '${{ secrets.HARBOR_USER }}' --password-stdin
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{env.HARBOR_SERVER}}
        username: ${{secrets.HARBOR_USER}}
        password: ${{secrets.HARBOR_PASSWORD}}



    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{env.IMAGE_NAME}}
        docker tag ${{env.IMAGE_NAME}} {{env.IMAGE_NAME}}:{{env.V6_TAG}}

    - name: Push the Docker images
      run: |
        docker push $IMAGE_NAME
        docker push {{env.IMAGE_NAME}}:{{env.V6_TAG}}
      
      
