name: Docker Image CI

on:
  push:
    branches: [ master ]



jobs:

  docker-push:
    env:
      IMAGE_NAME: "harbor.carrier-mu.src.surf-hosted.nl/carrier/n2n-diagnostics"
      HARBOR_SERVER: "harbor.carrier-mu.src.surf-hosted.nl"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      #run: echo '${{ secrets.HARBOR_PASSWORD }}' | docker login ${{env.HARBOR_SERVER}} --username '${{ secrets.HARBOR_USER }}' --password-stdin
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{env.HARBOR_SERVER}}
        username: ${{secrets.HARBOR_USER}}
        password: ${{secrets.HARBOR_PASSWORD}}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{env.IMAGE_NAME}}

    - name: Push the Docker image
      run: docker push $IMAGE_NAME
      
      
